### ISSUE TITLE
Need a few documentation to start with existing schema

### ISSUE THREAD

**Issue by rccc** [hasura-extra/symfony-app#9]
Hello,

First, many thanks to give us the opportunity to work with Hasura and Symfony.

I have an existing GRAPHQL schema build on top of Postgres with Hasura.

I look at the source, i understand that we can generate some code with hasura:sailor:command  but it is not clear for me if the Hasura directory contains the same data generated by hasura and if this command use the data inside the Hasura directory.

Many thanks in advance,
i wish you a nice day
Eric

**Comment by vuongxuongminh** [comment]
Hi @rccc, [Sailor is type safe graphql client generator](https://github.com/spawnia/sailor/) it help you generate PHP code from your graphql query.

**Comment by rccc** [comment]
@vuongxuongminh,
Hi, many thanks for response and advice.
I wish you a nice day.
